/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NewtonRaphson */

#ifndef _Included_NewtonRaphson
#define _Included_NewtonRaphson
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NewtonRaphson
 * Method:    calcularRaiz
 * Signature: (DID)D
 */
JNIEXPORT jdouble JNICALL Java_NewtonRaphson_calcularRaiz
  (JNIEnv *, jobject, jdouble, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
